import {Header,Footer,Button,Steps,Testimonials,Newsletter,ServiceCards} from './site';
export default function Home(){const proof=['dieter','pamela-palos','robert','monika','pamela'];return <main>
<Header/>
<section className="home-hero"><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/>
  <div className="hero-content"><p className="kicker">Career & expat coaching · English + German</p><h1>Career change feels easier when you don’t have to figure it out alone.</h1><p className="hero-lead">Calm, practical coaching for international professionals who want more clarity, confidence and direction in their next career chapter.</p><div className="hero-actions"><Button href="/book">Book a Free Intro Session</Button><a href="/coaching-approach">See how coaching works →</a></div><div className="hero-proof"><div className="proof-portrait">{proof.map(x=><img src={`/client-${x}.png`} alt="Client" key={x}/>)}</div><p><b>Personal coaching with Nina</b><small>Real words from professionals Nina has supported</small></p><div className="proof-stars"><b>★★★★★</b><small>Clarity, confidence, direction</small></div></div></div>
  <div className="hero-visual"><div className="visual-note note-one"><b>Clarity</b><small>Know what matters next</small></div><div className="visual-note note-two"><b>Confidence</b><small>Own your career story</small></div><div className="visual-note note-three">Direction <span>↗</span></div><div className="portrait-card"><img src="/nina-headshot.png" alt="Nina Sterngold, career and expat coach"/><div><b>Nina Sterngold</b><small>Career & Expat Coach</small></div></div><div className="visual-caption"><span>01</span><p>A calm space for your<br/><b>next career chapter.</b></p></div></div>
</section>
<section className="trust"><div className="trust-track">{[0,1].map(row=><div key={row}><span>Coaching since 2017</span><span>English + German</span><span>ICF Member</span><span>Career & Expat Coaching</span></div>)}</div></section>
<section className="split intro-section"><p className="eyebrow">Who I help</p><div><h2>You don’t need to have the whole plan. You just need a place to start.</h2><p className="large-copy">I work with international professionals, expats, job seekers and people in transition who feel stuck, overwhelmed or unsure which direction to take next.</p></div></section>
<section className="nina-editorial"><div><p className="eyebrow">A human conversation</p><h2>Space to think clearly. Support to move forward.</h2><p>You don’t need another generic framework. You need <b>thoughtful questions</b>, honest reflection, and <b>practical steps</b> shaped around your real life.</p><Button href="/about">Meet Nina</Button></div><div className="cutout-stage"><span>Calm</span><span>Practical</span><span>Personal</span><span className="float-star">✦</span><span className="float-ring">◎</span><img src="/nina-cutout.png" alt="Nina Sterngold in a coaching conversation"/></div></section>
<section className="problem-band"><p className="eyebrow">Does this feel familiar?</p><div className="problem-grid"><article><span>01</span><h3>You’ve outgrown your role</h3><p>Your work no longer fits, but the next step still feels unclear.</p></article><article><span>02</span><h3>Too many possibilities</h3><p>You have ideas, but struggle to choose a direction and commit to it.</p></article><article><span>03</span><h3>Your confidence dipped</h3><p>A move, job search or career pause has made it harder to see your value.</p></article></div></section>
<ServiceCards/><section className="process"><div><p className="eyebrow">How coaching works</p><h2>A thoughtful process that turns uncertainty into forward movement.</h2></div><Steps/></section><Testimonials/><Newsletter/><section className="final-cta"><p className="eyebrow">Your next chapter</p><h2>Ready to find your next direction?</h2><p>Let’s talk about where you are now, what you want to change, and how coaching could help.</p><Button href="/book" light>Book a Free Intro Session</Button></section><Footer/>
</main>}
